events
{
    worker_connections 1024;
}

http
{
    include /etc/nginx/mime.types;
    default_type application/octet_stream;

    server
    {
        listen 443 ssl;
        listen [::]:443 ssl;

        server_name ialalawn.42.fr;

        ssl_certificate /etc/ssl/web/certs/pub.crt;
        ssl_certificate_key /etc/ssl/web/private/pri.key;

        ssl_protocols TLSv1.2 TLSv1.3;

        root /var/website/html;
        index index.php index.html;

        location / {
            try_files $uri $uri/ /index.php?$args;
        }

        location ~\.php$ {
            include snippets/fastcgi-php.conf;
            fastcgi_pass wordpress:9000;
        }
    }
}